services:
  db:
    image: postgres:15-alpine
    container_name: oasis_database
    environment:
      POSTGRES_USER: oasis
      POSTGRES_PASSWORD: "281fe2f0" # Use quotes to be safe
      POSTGRES_DB: oasis_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
